# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Documentation Coach AAC
title: Documentation Coach AAC
email: equipe@coachaac.com
description: >- # this means to ignore newlines until "baseurl:"
  Vous êtes parent d’un jeune en conduite accompagnée (AAC) ? Coach AAC est fait pour vous !
  Coach AAC facilite le suivi et la progression de votre jeune en conduite accompagnée.
baseurl: "/coachaac" # the subpath of your site, e.g. /blog
url: "https://coachaac.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


exclude: [vendor,Gemfile,Gemfile.lock,Rakefile,readme.md]
canonical_domain: https://www.coachaac.com
assets:
  js_compressor:  uglifier
  css_compressor: sass
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
